# This workflow tries building parameters from the circuits.

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - name: Cache circom
      id: cache-circom
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/circom
        # Since the version of circom is specified in `scripts/install-circom.sh`,
        # as long as the file doesn't change we can reuse the circom binary.
        key: ${{ runner.os }}-circom-${{ hashFiles('./scripts/install-circom.sh') }}
    - run: npm ci
    - run: npm run build
